[build]
  command = "npm run build"
  publish = "dist"
<<<<<<< HEAD
=======
  functions = "netlify/functions"
>>>>>>> fix/password-reset-otp-admin-api

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
